In [126]:
import pandas as pd
import numpy as np
import seaborn as sea
import matplotlib.pyplot as plt
%matplotlib inline

In [127]:
from kagglehub.datasets import dataset_download
import kagglehub
from google.colab import userdata

KAGGLE_API_KEY = userdata.get('KAGGLE_API_KEY')

#Downloading using kagglehub.dataset_download
dataset_handle = "yash9439/ipl-dataset"
path = kagglehub.dataset_download(dataset_handle)

print(f"Path to dataset files: {path}")

Using Colab cache for faster access to the 'ipl-dataset' dataset.
Path to dataset files: /kaggle/input/ipl-dataset

#1. First dataset cleaning

In [128]:
# import_dataset
dataset = pd.read_csv(f"/kaggle/input/ipl-dataset/deliveries.csv")

In [129]:
#5_records_of_the_dataset_deliveries
dataset.head(9)

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
0,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,1,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
1,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,2,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
2,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,3,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
3,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,4,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
4,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,5,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,2,2,NaN,NaN,NaN
5,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,6,S Dhawan,DA Warner,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
6,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,7,S Dhawan,DA Warner,TS Mills,0,...,0,1,0,0,0,1,1,NaN,NaN,NaN
7,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,2,1,S Dhawan,DA Warner,A Choudhary,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
8,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,2,2,DA Warner,S Dhawan,A Choudhary,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN

In [130]:
#Rows_columns_and_datatypes_in_dataset_using_pd.info()
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150460 entries, 0 to 150459
Data columns (total 21 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   match_id          150460 non-null  int64
 1   inning            150460 non-null  int64
 2   batting_team      150460 non-null  object
 3   bowling_team      150460 non-null  object
 4   over              150460 non-null  int64
 5   ball              150460 non-null  int64
 6   batsman           150460 non-null  object
 7   non_striker       150460 non-null  object
 8   bowler            150460 non-null  object
 9   is_super_over     150460 non-null  int64
 10  wide_runs         150460 non-null  int64
 11  bye_runs          150460 non-null  int64
 12  legbye_runs       150460 non-null  int64
 13  noball_runs       150460 non-null  int64
 14  penalty_runs      150460 non-null  int64
 15  batsman_runs      150460 non-null  int64
 16  extra_runs        150460 non-null  int64
 17  total_runs        150460 non-null  int64
 18  player_dismissed  7438 non-null    object
 19  dismissal_kind    7438 non-null    object
 20  fielder           5369 non-null    object
dtypes: int64(13), object(8)
memory usage: 24.1+ MB

In [131]:
#Let_us_know_how_many_NaN_features_we_have
display(dataset.isnull().sum())

match_id                 0
inning                   0
batting_team             0
bowling_team             0
over                     0
ball                     0
batsman                  0
non_striker              0
bowler                   0
is_super_over            0
wide_runs                0
bye_runs                 0
legbye_runs              0
noball_runs              0
penalty_runs             0
batsman_runs             0
extra_runs               0
total_runs               0
player_dismissed    143022
dismissal_kind      143022
fielder             145091
dtype: int64

we_need_to_address_these_three_features
player_dismissed	143022
dismissal_kind	143022
fielder	145091

In [132]:
#Let_us_use_pd.describe_function
display(dataset.describe())

,match_id,inning,over,ball,is_super_over,wide_runs,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs
count,150460.000000,150460.000000,150460.000000,150460.000000,150460.000000,150460.000000,150460.000000,150460.000000,150460.000000,150460.000000,150460.000000,150460.000000,150460.000000
mean,318.281317,1.482188,10.142649,3.616483,0.000538,0.037498,0.004885,0.022232,0.004340,0.000066,1.222445,0.069022,1.291466
std,182.955531,0.501768,5.674338,1.807698,0.023196,0.257398,0.114234,0.200104,0.072652,0.018229,1.594509,0.349667,1.583240
min,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,161.000000,1.000000,5.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,319.000000,1.000000,10.000000,4.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,1.000000
75%,476.000000,2.000000,15.000000,5.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,1.000000
max,636.000000,4.000000,20.000000,9.000000,1.000000,5.000000,4.000000,5.000000,5.000000,5.000000,6.000000,7.000000,7.000000

In [133]:
dataset.columns

Index(['match_id', 'inning', 'batting_team', 'bowling_team', 'over', 'ball',
       'batsman', 'non_striker', 'bowler', 'is_super_over', 'wide_runs',
       'bye_runs', 'legbye_runs', 'noball_runs', 'penalty_runs',
       'batsman_runs', 'extra_runs', 'total_runs', 'player_dismissed',
       'dismissal_kind', 'fielder'],
      dtype='object')

In [134]:
#Top10_bowler_that_gave_least_run
#Top10_bowler_that_gave_most_run
#Top_10_batsmen_who_scored_most_run
#Top_10_who_scored_least_run
#Most_wide_bowler
# most_no_balls_player
#Most_wide_ball_player_
#Most_dismissals
#All_matchups
#Super_over_max_runs.
#teams_who_gave_extra_runs
#most_wicket_by_dismissal_kind
#player_who_dismissed_the_most

In [135]:
dataset['player_dismissed'].value_counts()

player_dismissed
SK Raina        134
G Gambhir       131
RG Sharma       129
RV Uthappa      128
V Kohli         118
               ...
BE Hendricks      1
JD Unadkat        1
M de Lange        1
S Kaushik         1
KJ Abbott         1
Name: count, Length: 436, dtype: int64

In [136]:
delivery_dataset = dataset.copy()

In [137]:
numerical_columns = [feature for feature in delivery_dataset.columns if dataset[feature].dtype != 'object' and feature not in ['match_id','inning']]
display(numerical_columns)

['over',
 'ball',
 'is_super_over',
 'wide_runs',
 'bye_runs',
 'legbye_runs',
 'noball_runs',
 'penalty_runs',
 'batsman_runs',
 'extra_runs',
 'total_runs']

In [ ]:
#Using dataset.melts fro visualising multiple numerical columns using box plot.
melted_data_before_capping = delivery_dataset.melt(
                    value_vars= numerical_columns,var_name='Numerical Feature',
                    value_name='Value')

#Create a sigle figure with subplots for each box plot.
plt.figure(figsize=(15,10))
sea.boxplot(x='Numerical Feature',y='Value', hue='Numerical Feature',
            data=melted_data_before_capping,palette='viridis', legend=False)
plt.title("Box Plot of All Numerical Features")
plt.xlabel('Numerical Features')
plt.ylabel("Value")
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()

"i" decided to keep the dataset with outliers because you found that the capping process "ruined the data." In the context of cricket, what might appear as a statistical outlier can often be a meaningful and crucial data point, and you preferred to retain the original distribution and its contextual significance.

In [ ]:
# player_dismissed	143022
# dismissal_kind	143022
# fielder	145091

delivery_dataset['player_dismissed']= delivery_dataset['player_dismissed'].fillna("not out")

delivery_dataset['dismissal_kind'] = delivery_dataset['dismissal_kind'].fillna("N/A")

delivery_dataset['fielder'] = delivery_dataset['fielder'].fillna("N/A")

In [ ]:
delivery_dataset.isnull().sum()

In [ ]:
print(f"Number of duplicate rows: {delivery_dataset.duplicated().sum()}")

In [ ]:
delivery_dataset.drop_duplicates(inplace=True)

In [ ]:
print(f"Number of duplicate rows after dropping: {delivery_dataset.duplicated().sum()}")